services:
  app:
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT}
      TG_TOKEN: ${TG_TOKEN}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET:-}
      WEBHOOK: ${WEBHOOK}
      DEBOUNCE_TIME: ${DEBOUNCE_TIME:-}
      DB_PATH: ${DB_PATH:-/app/data/db.sqlite}
    volumes:
      - ./:/app/
    ports:
      - $PORT:$PORT
    command: node --watch index.js
    restart: unless-stopped
